### ISSUE TITLE
Editor for type "markdown" loses focus after every keystroke

### ISSUE THREAD

**Issue by floriandotpy** [agentejo/copilot#3]
I have a markdown field. The editor renders correctly. However, if I type, it loses focus and have to click in the editor again. Maybe the editor is re-rendered every time? Seems like a bug.

The editor for the default content field works as it should.

My type is defined as follows:

```
label: Member
ext: md
meta:
    text:
        type: markdown
        label: Description Text
```
